name: 构建iOS应用

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  buildAndroid:
    runs-on: macos-latest
    name: 构建iOS
    
    steps:
      - name: 检查
        uses: actions/checkout@v3

      - name: 安装.NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: 安装iOS工作负载
        run: dotnet workload install ios

      - name: 安装Xcode
        uses: BoundfoxStudios/action-xcode-select@v1
        with:
          version: "14.2"

      - name: 构建
        run: |
          cd SealOrder.iOS
          dotnet build -c Release
          cd bin/Release/
          ls
